### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by NehaK275**

### CODE REVIEW

**Comment by AndreaTorti-01** [comment]
Can I ask you what was your intention?

**Comment by NehaK275** [comment]
> Can I ask you what was your intention?
I have made jdk in place of jre as you have mentioned in the issue.

**Comment by NehaK275** [comment]
> > Can I ask you what was your intention?
> > I have made jdk in place of jre as you have mentioned in the issue.

Is this wrong?

**Comment by AndreaTorti-01** [comment]
This is not how java works, jre and jdk are completely different builds,
and the .jar is the extension or a java runnable file. what you need to
write, if you want to contribute, is a platform detector and downloader for
a java jre that links to an api of a website offering java builds (oracle
does not distribute them now)

Il giorno lun 7 mar 2022 alle ore 14:33 NehaK275 ***@***.***>
ha scritto:

**Pull request closed without merging**
